---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: master

run:
  path: master/ci/scripts/deploy.sh

params:
  ENVIRONMENT:
  DEPLOY_WEBHOOK_PASSWORD:
  PROJECT:
