---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: repo

run:
  path: /bin/sh
  args: ['repo/ci/scripts/deploy.sh']

params:
  ENVIRONMENT:
  DEPLOY_WEBHOOK_PASSWORD:
  PROJECT:
