---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/brodyd795/secret-message.git
      branch: master

jobs:
  - name: deploy
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build
        file: repo/ci/tasks/build.yml
